### ISSUE TITLE
Getting Error while run gulp jsx

### ISSUE THREAD

**Issue by venkateswararao** [WordPress-Admin-JavaScript-Boilerplate/ReactJS-Boilerplate#3]
Getting error while run gulp jsx  command the error message is "'jsx-shell errored  Error: Command `jsx ./assets/js/ ./build/js/tmp` failed with exit code 1   at ChildProcess.exithandler child_process.js:213:12)"

![error](https://cloud.githubusercontent.com/assets/2831915/13631821/96281f66-e60c-11e5-8eca-c11ef178e23f.png)

let me know how to resolve this issue?

**Comment by royboy789** [comment]
Sorry, but you'll probably need to install jsx globall `npm install -g jsx`
https://www.npmjs.com/package/jsx

**Comment by venkateswararao** [comment]
After install jsx  globally still getting same error 


![error1](https://cloud.githubusercontent.com/assets/2831915/13659042/037bba50-e6a3-11e5-8625-67fc1fe8e77c.png)

**Comment by royboy789** [comment]
@venkateswararao are you sure jsx is defined? 

never seen that issue before. let me try a fresh install and see if I get the same error.

**Comment by venkateswararao** [comment]
roy, i fixed this issue using browserify and reactify  to transform jsx files to js

**Comment by venkateswararao** [comment]
Roy, let me know how to use custom api  in list-posts.js ?  "admin_custom_api.php"  file  you already define books api  instead of book i want to use  /wp/v2/books  in list-posts.js  getting 404 error how can i use coustom  api  in "list-posts.js"

**Comment by royboy789** [comment]
If you are changing the CPT, you will need to make sure the endpoint works first. Go to yourdomain.com/wp-json to see all routes available, then change line 11 to match:
https://github.com/WordPress-Admin-JavaScript-Boilerplate/ReactJS-Boilerplate/blob/master/assets/js/components/list-posts.js#L11

**Comment by avclark** [comment]
Hi Roy, 

I'm getting an error when running "gulp jsx". Can't seem to figure out what's going on. 

<img width="1680" alt="screen shot 2017-04-17 at 1 25 06 am" src="https://cloud.githubusercontent.com/assets/843034/25079721/cdd53e56-230c-11e7-807c-58fec4d4cb8e.png">

Any ideas?
